version: '3'

services:
  db:
    image: mysql
    container_name: db_symfony_blog
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      - dev

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin_symfony_blog
    depends_on:
      - db
    ports:
      - "8888:80"  # Changement du port externe pour phpMyAdmin
    environment:
      PMA_HOST: db
    networks:
      - dev

  www:
    build: docker
    container_name: www_symfony_blog
    ports:
      - "8001:80"  # Changement du port externe pour Symfony
    volumes:
      - ./docker/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www
    networks:
      - dev

networks:
  dev:

volumes:
  db-data:
